jQuery.fn.exists=function(callback){var args=[].slice.call(arguments,1);if(this.length){callback.call(this,args);}
return this;};jQuery.fn.isOnScreen=function(){var win=jQuery(window);var viewport={top:win.scrollTop(),left:win.scrollLeft()};viewport.right=viewport.left+ win.width();viewport.bottom=viewport.top+ win.height();var bounds=this.offset();bounds.right=bounds.left+ this.outerWidth();bounds.bottom=bounds.top+ this.outerHeight();return(!(viewport.right<bounds.left||viewport.left>bounds.right||viewport.bottom<bounds.top||viewport.top>bounds.bottom));};jQuery(document).ready(function($){jQuery("body").prepend("<a id='move-to-top' class='animate ' href='#blog'><i class='fa fa-chevron-up'></i></a>");var scrollDes='html,body';if(navigator.userAgent.match(/opera/i)){scrollDes='html';}
jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>160){jQuery('#move-to-top').addClass('filling').removeClass('hiding');}else{jQuery('#move-to-top').removeClass('filling').addClass('hiding');}});});jQuery(document).ready(function($){var scrollToAnchor=function(id,event){var elem=$("a[name='"+ id+"']");if(typeof(elem.offset())==="undefined"){elem=$("#"+id);}
if(typeof(elem.offset())!=="undefined"){event.preventDefault();var scroll_to=elem.offset().top;$('html, body').animate({scrollTop:scroll_to},600,'swing',function(){if(scroll_to>46)window.location.hash=id;});}};$("a").click(function(event){var href=$(this).attr("href");if(href&&href.match("#")&&href!=='#'){var parts=href.split('#'),url=parts[0],target=parts[1];if((!url||url==window.location.href.split('#')[0])&&target)
scrollToAnchor(target,event);}});});if(mts_customscript.responsive&&mts_customscript.nav_menu!='none'){jQuery(document).ready(function($){if(mts_customscript.nav_menu=='both'){$('#navigation').not('.mobile-menu-wrapper').find('.menu').clone().appendTo('.mobile-menu-wrapper').hide();}
$('.toggle-mobile-menu').click(function(e){e.preventDefault();e.stopPropagation();$('body').toggleClass('mobile-menu-active');});$(document).on('DOMMouseScroll mousewheel','.mobile-menu-wrapper',function(ev){var $this=$(this),scrollTop=this.scrollTop,scrollHeight=this.scrollHeight,height=$this.height(),delta=(ev.type=='DOMMouseScroll'?ev.originalEvent.detail*-40:ev.originalEvent.wheelDelta),up=delta>0;var prevent=function(){ev.stopPropagation();ev.preventDefault();ev.returnValue=false;return false;}
if($('a#pull').css('display')!=='none'){if(!up&&-delta>scrollHeight- height- scrollTop){$this.scrollTop(scrollHeight);return prevent();}else if(up&&delta>scrollTop){$this.scrollTop(0);return prevent();}}});}).on('click',function(event){var $target=jQuery(event.target);if(($target.hasClass("fa")&&$target.parent().hasClass("toggle-caret"))||$target.hasClass("toggle-caret")){return;}
jQuery('body').removeClass('mobile-menu-active');});}
jQuery(document).ready(function($){function mtsDropdownMenu(){var wWidth=$(window).width();if(wWidth>865){$('#navigation ul.sub-menu, #navigation ul.children').hide();var timer;var delay=100;$('#navigation li').hover(function(){var $this=$(this);timer=setTimeout(function(){$this.children('ul.sub-menu, ul.children').slideDown('fast');},delay);},function(){$(this).children('ul.sub-menu, ul.children').hide();clearTimeout(timer);});}else{$('#navigation li').unbind('hover');$('#navigation li.active > ul.sub-menu, #navigation li.active > ul.children').show();}}
mtsDropdownMenu();$(window).resize(function(){mtsDropdownMenu();});});jQuery(document).ready(function($){$('.widget_nav_menu, #navigation .menu').addClass('toggle-menu');$('.toggle-menu ul.sub-menu, .toggle-menu ul.children').addClass('toggle-submenu');$('.toggle-menu ul.sub-menu').parent().addClass('toggle-menu-item-parent');$('.toggle-menu .toggle-menu-item-parent').append('<span class="toggle-caret"><i class="fa fa-plus"></i></span>');$('.toggle-caret').click(function(e){e.preventDefault();$(this).parent().toggleClass('active').children('.toggle-submenu').slideToggle('fast');});});jQuery(document).ready(function($){$('.share-item a').on('click',function(){newwindow=window.open($(this).attr('href'),'','height=330,width=750');if(window.focus){newwindow.focus()}
return false;});(function(d,s){var js,fjs=d.getElementsByTagName(s)[0],load=function(url,id){if(d.getElementById(id)){return;}
js=d.createElement(s);js.src=url;js.id=id;fjs.parentNode.insertBefore(js,fjs);};jQuery('span.facebookbtn, .facebook_like').exists(function(){load('//connect.facebook.net/en_US/all.js#xfbml=1','fbjssdk');});jQuery('span.twitterbtn').exists(function(){load('//platform.twitter.com/widgets.js','tweetjs');});}(document,'script'));});jQuery(document).ready(function($){var lazyloadAvatar=function(){$('.comment-author .avatar').each(function(){var distanceToTop=$(this).offset().top;var scroll=$(window).scrollTop();var windowHeight=$(window).height();var isVisible=distanceToTop- scroll<windowHeight;if(isVisible){var hashedUrl=$(this).attr('data-src');if(hashedUrl){$(this).attr('src',hashedUrl).removeClass('loading');}}});};if($('.comment-author .avatar').length>0){$('.comment-author .avatar').each(function(i,el){$(el).attr('data-src',el.src).removeAttr('src').addClass('loading');});$(function(){$(window).scroll(function(){lazyloadAvatar();});});lazyloadAvatar();}});jQuery(document).ready(function($){$('.head-search').on('click','.search-trigger',function(e){var $form=$(this).next('#searchform');$form.stop().fadeToggle();$form.find('#s').focus();e.stopPropagation();e.preventDefault();});$('#header').on('click','#searchform',function(e){e.stopPropagation();});$(document).on('click',function(e){$('#header #searchform').stop().fadeOut();});});function mts_loadTabContent(tab_name,page){var container=jQuery('#tab-content');var tab_content=jQuery(tab_name);if(!page)page=1;var isLoaded=parseInt(tab_content.data('loaded'))||0;if(isLoaded<page){if(!container.hasClass('mts-loading')){container.addClass('mts-loading');if(page>1){tab_content=tab_content.append('<div class="more-page-'+page+'"></div>').find('.more-page-'+page);}
tab_content.load(mts_customscript.ajax_url,{action:'mts_home_tabs_content',tab:tab_name,page:page},function(){container.removeClass('mts-loading');if(page==1){tab_content.data('loaded',page).hide().fadeIn().siblings().hide();}else{tab_content.hide().fadeIn().parent().data('loaded',page);tab_content.parent().find('[id=load-posts]').hide().last().show();}});}}else{tab_content.fadeIn().siblings().hide();}}
jQuery(document).ready(function($){$('#tab-group li').on('click','a',function(e){var $this=$(this);e.preventDefault();$this.parent().addClass('active').siblings().removeClass('active');var tab_name=$this.attr('href'),tab_name=tab_name+'-content';mts_loadTabContent(tab_name);});$('#tab-group li').first().find('a').click();if(mts_customscript.home_pagenavigation==2){var loading_posts=false;var last_post=false;var page=1;$(window).scroll(function(){var lastPostVisible=$('.latestPost').last().isOnScreen();if(lastPostVisible){loading_posts=true;var $button=$('#tab-content #load-posts > a').last();var page=parseInt($button.data('page'));var tab_name=$button.data('tab');mts_loadTabContent(tab_name,page);}});}else{$('#tab-content').on('click','#load-posts > a',function(e){e.preventDefault();var $this=$(this);if($this.is('.disabled'))
return true;var page=parseInt($this.data('page'));var tab_name=$this.data('tab');mts_loadTabContent(tab_name,page);});}
$('#tab-content.single').on('click','#load-posts > a',function(e){e.preventDefault();var $this=$(this);if($this.is('.disabled'))
return true;var page=parseInt($this.data('page'));var tab_name=$this.data('tab');mts_loadTabContent(tab_name,page);});});